apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-wgyk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-wgyk
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-wgyk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-wgyk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-wgyk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-service-e2e-tenant/appstudio/dc-metro-map-wgyk@sha256:a2d1b9ec07fe56d34d24b048ca6160b717f5931924fc337c2dac2bf4e9af2b36
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
